config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resources :posts
  resources :comments
  get'/login',   to: 'sessions#login'
  post   '/login',   to: 'sessions#create'
  post '/createpost',to:'posts#create'
  post '/createcomment',to: 'comments#create'
  get '/logout',to:'sessions#destroy'
  root 'users#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comment
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true
  has_secure_password
  has_many :post
  has_many :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    else
      redirect_to login_path
    end
  end
  # def correct_user
  #   unless params[:user_id]!=session[:user_id] ?
  #     flash[:danger] = "You can't visit this page."
      
  #   end
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :current_user, only:[:create]
  def create
    @post= Post.find_by(user_id: params[:comment][:user_id], id:params[:comment][:post_id])
    
    @comment = @post.comment.build(comment_params)
    if @comment.save
      redirect_to root_path
    else
      render 'posts/show'
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:body,:user_id)
    # params.require(:post).permit(:content)\
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :current_user, only:[:create]
  def create
    # current_user.microposts.build(micropost_params)
      @post = current_user.post.build(micropost_params)
     
      if @post.save
        flash[:success] = "Micropost created!"
        redirect_to users_path
      else
        @post
         render 'users/show'
      end
  end
  def show
    @post=Post.find(params[:id])
    # @current_user=current_user
    @id=@post.user_id
    @post_id=@post.id
    @comment = @post.comment.build
  end
  private
    
  def micropost_params
    params.require(:post).permit(:context)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end
  def create
    user = User.find_by(email:params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to user
      else
        flash[:danger] = 'Invalid email/password combination' # Not quite right!
        render 'login'
      end
  end
  def destroy
    session.delete(:user_id)
    #log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only:[:show,:home]
  def new
    @user =User.new
  end
  def create
    # @user=User.new(params.require(:user).permit(:name, :email, :password, :confirm_password))
    @user = User.new(user_params)
    if @user.save
      flash[:success]="User Created Successfully"
      redirect_to @user
    else
      render 'new'
    end
  end
  def show
    @user=User.find(params[:id])
    # @post = current_user.post.build
    @id=@user.id
    @posts= @user.post.includes(:comment)
    # @posts.each do |post|
    #   @comment = post.comment.build
    # end
  end
  def home
    if session[:user_id]
    @user=User.find(session[:user_id])
    @post = current_user.post.build
    end
  end
  def index
    @users=User.all  
  end
  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_name(comments)
    @user_name= comments.user.name
    return @user_name
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id]=user.id
  end
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_user_comment.html.erb
<%= form_with(model: @comment, local: true) do |f| %>
  <%f.label :body %>
    <%= f.text_area(:body, rows: 1, data: {provide: "markdown"})%>
    <%= f.hidden_field :user_id, required: true, class: 'form-control', value:@id  %>
    <%= f.hidden_field :post_id, required: true, class: 'form-control', value:@post_id  %>
  <%=f.submit "comment!",class:'btn btn-primary'%>
<%end%>

app/views/layouts/_footer.html.erb
<footer class="footer">
 <small>
   The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
   by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
</small>
<nav>
  <ul>
    <li><%= link_to "About", '#' %></li>
    <li><%= link_to "Contact", '#' %></li>
    <li><a href="https://news.railstutorial.org/">News</a></li>
  </ul>
 </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Log out", '/logout', method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <%= link_to "Settings", edit_user_path(current_user) %>
              <li class="divider"></li>
              <li>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/posts/_new_post.erb
<%# <div class="container"> %>
  <div class="col-md-12">
    <%= form_with(model: @post, local: true) do |f| %>
       <div class="col-md-12">
        <%f.label :context %>
        <%= f.text_area(:context, rows: 4, data: {provide: "markdown"})%>
      </div>
      <div class="col-md-12">
        <%=f.submit "createPost!",class:'btn btn-primary'%>
      </div>
      <%end%>
  </div>
<%# </div> %>

app/views/posts/show.html.erb
<h1>Show single post</h1>
<div class="container">
  <%=@post.context%>
  <div class="comment_div">
    <%= render"comments/user_comment"%>
  </div>
</div>

app/views/users/_error_msg.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |msg| %>
    <%= msg %>
<% end %>
<% end %>

app/views/users/_flash_msg.html.erb
<% flash.each do|type,msg|%>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/users/home.html.erb
<div class="container">
    <h1 class="title">Profile Page!</h1>
  <% if session[:user_id] %> 
  <div class="main-container">
    <div class="col-md-12">
      <%= @user.name %>
    </div>
    <div class="col-md-12">
      <%= @user.email %>
    </div>
    <div class="col-md-12">
      <%= render "posts/new_post" %>
    </div>
  </div>
  <%else%>
      <%=link_to "Login Please!",login_path%>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="title">
    <h1>All User</h1>
  </div>
   <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>View Post</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do|user|%>
        <tr>
          <td>
            <%= user.name %>
          </td>
          <td>
            <%= user.email %>
          </td>
          <td>
            <%= link_to "Visit User!",user_path(user) %>
          </td>
        </tr>
      <%end%>
    </tbody>
</div>

app/views/users/new.html.erb
<h1>Sing up Form!</h1>
<%= render 'error_msg', object: @user %>
<div class="container">
  <div class="row">
    <%= form_with(model: @user, local: true) do |f|%>
      <div class="col-md-12">
        <%= f.label :name %>
        <%= f.text_field :name ,class: 'form-control' %>
      </div>
      <div class="col-md-12">
        <%= f.label :email %>
        <%= f.email_field :email ,class: 'form-control' %>
      </div>
      <div class="col-md-12">
        <%= f.label :password %>
        <%= f.password_field :password ,class: 'form-control'%>
      </div>
      <div class="col-md-12">
        <%= f.label :confirm_password %>
        <%= f.password_field :confirm_password ,class: 'form-control'%>
      </div>
      <div class="col-md-12">
        <%= f.submit "sign up!" , class: "btn btn-primary" %>
        <%= link_to 'Already have an account Login please!', login_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome User</h1>
<%# <% flash.any? %>
<%# < %= render " users/flash_msg" %>
<%# < % end %>  
<div class="container">
     <div class="col-md-6 col-md-3-offset"> 
        <div class="post_div">
          <% @posts.each do|post| %>
            <div class="col-md-12">
              <div class="post_container">
                <div class="media">
                <div class="media-body">
                  <h4 class="media-heading"><%= @user.name%><small><i>Posted on <%=@user.created_at.strftime("%Y-%m-%d")%></i></small></h4>
                  <p><%=post.context%></p>
                    <div class="comments">
                      <%= post.comment.each do|comments|%>
                      <div class="media">
                        <div class="media-body">
                          <h4 class="media-heading"><%=comments_name(comments) %><small><i>Commented on <%=comments.created_at.strftime("%Y-%m-%d")%></i></small></h4>
                                <div class="col-md-12">
                                <% if comments.body %>
                                <%=comments.body%>
                                <% end %>
                              </div>
                          </div>
                        </div>
                      <%end%> 
                  </div>
                </div>
              </div>
              </div>
              <%= link_to 'View Post',post_path(post)%>
            </div>
          <% end %>  
        </div>
         
    </div>
  </div>
      